[package]
name = "bevy-aabb-instancing"
version = "0.4.2"
edition = "2021"
description = "Render millions of AABB instances in Bevy."
keywords = ["bevy", "aabb", "cube", "instancing", "render"]
license-file = "LICENSE"
repository = "https://github.com/ForesightMiningSoftwareCorporation/bevy-aabb-instancing/"

[features]
trace = ["bevy/trace_chrome"]

[dependencies]
ahash = "0.7"

[dependencies.bevy]
version = "0.8"
default-features = false
features = ["bevy_asset", "bevy_core_pipeline", "bevy_render", "x11"]

[dev-dependencies]
rand = "0.8"
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras", rev = "a1095b9bc" }
